#include <iostream>
using namespace std;
int main()
{
   
   string a;
   cout<<"=====REUNI_SMA======";
   cin>>a;
   if(a=="IPHONE 15")
   {
     cout<<"SILAHKAN MASUK BAGINDA;)"<<endl;
   }
   else if(a=="IPHONE 14")
   {
     cout<<"SILAHKAN MASUK TUAN:)"<<endl;
   }
   else if(a=="IPHONE 13 ")
   {
    cout<<"SILAHKAN MASUK KAKAK"<<endl;
   }
   else
   {
     cout<<"ANDROID/MISKIN JGN NSK:["<<endl;
   }

}